name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env File
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "amqp=${{ secrets.amqp }}" >> .env
          echo "amqpSend=${{ secrets.amqpSend }}" >> .env

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: planar-night-441205-d0

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/email-service-backend/email-service-backend:$GITHUB_SHA .

      - name: Push Docker image to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker push us-central1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/email-service-backend/email-service-backend:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy email-service-backend \
            --image us-central1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/email-service-backend/email-service-backend:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
