name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Authenticate using google-github-actions/auth action
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: planar-night-441205-d0

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/email-service-backend/email-service-backend:$GITHUB_SHA .

    # Push Docker image to Google Artifact Registry
    - name: Push Docker image to Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker push us-central1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/email-service-backend/email-service-backend:$GITHUB_SHA

    # Deploy the image to Google Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy email-service-backend \
          --image us-central1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/email-service-backend/email-service-backend:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
